# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBWt_lCmjCcftEk17GiWmtspMb6xHtaU
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
import matplotlib.pyplot as plt
import io
import requests
from sklearn.model_selection import train_test_split



class Model(nn.Module):
    def __init__(self, in_features=4, h1=8, h2=8, out_features=3):
      super().__init__()
      self.fc1 = nn.Linear(in_features, h1)
      self.fc2 = nn.Linear(h1, h2)
      self.out = nn.Linear(h2, out_features)

    def forward(self, x):
      x = F.relu(self.fc1(x))
      x = F.relu(self.fc2(x))
      x = self.out(x)
      return x

torch.manual_seed(42)
model = Model()


# Iris CSV Data
url = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'

response_data = requests.get(url).content


# Workaround for SSL verfication error
csv_dataframe = pd.read_csv(io.StringIO(response_data.decode('utf-8')))

#csv_dataframe = pd.read_csv(url)

csv_dataframe['species'] = csv_dataframe['species'].map({'setosa':0.0, 'versicolor':1.0, 'virginica':2.0})

x_array = csv_dataframe.drop('species', axis=1).values

y_array = csv_dataframe['species'].values



x_train, x_test, y_train, y_test = train_test_split(x_array, y_array, test_size=0.2, random_state=42)

x_train = torch.FloatTensor(x_train)

x_test = torch.FloatTensor(x_test)

y_train = torch.LongTensor(y_train)

y_test = torch.LongTensor(y_test)



criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

epochs = 100

losses = []


for i in range(epochs):
  y_pred = model.forward(x_train)
  loss = criterion(y_pred, y_train)
  losses.append(loss.detach().numpy())

  if i % 10 == 0:
    print(f'epoch: {i} loss: {loss}')

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

# Plot output 
plt.plot(range(epochs), losses)
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.show()



